name: Blog
description: Provides blog entity.
type: Curtis Tinkers CMS
recipes:
  - drupal_cms_content_type_base
  - drupal_cms_media
install:
  - comment
  - highlightjs_input_filter
  - views_rss_core
  - views_rss_media
config:
  actions:
    user.role.authenticated:
      grantPermission: 'use text format comment_format'
