name: Blog
description: Provides blog entity.
type: Curtis Tinkers CMS
recipes:
  - drupal_cms_content_type_base
  - drupal_cms_media
install:
  - canvas
  - canvas_stark
  - ckeditor5
  - comment
  - curtistinkers_theme
  - cva
  - highlightjs_input_filter
  - linkit
  - media
  - menu_link_content
  - node
  - scheduler
  - tagify
  - ui_icons_menu
  - views_rss_core
  - views_rss_media
config:
  actions:
    user.role.anonymous:
      grantPermissions:
        - 'access comments'
        - 'view media'
    user.role.authenticated:
      grantPermissions:
        - 'post comments'
        - 'access comments'
        - 'view media'
        - 'use text format comment_format'
    user.role.content_editor:
      grantPermissions:
        - 'create blog content'
        - 'delete own blog content'
        - 'edit own blog content'
        - 'edit own comments'
        - 'post comments'
        - 'skip comment approval'
        - 'access comments'
        - 'view media'
        - 'schedule publishing of nodes'
        - 'schedule publishing of taxonomy_term'
        - 'view scheduled content'
        - 'view scheduled taxonomy_term'
        - 'use text format comment_format'

