name: Blog
description: Provides blog entity.
type: Curtis Tinkers CMS
recipes:
  - curtistinkers_cms_comment
  - curtistinkers_cms_media
  - curtistinkers_cms_theme_components
  - drupal_cms_content_type_base
  - drupal_cms_seo_tools
install:
  - ckeditor5
  - comment
  - content_moderation
  - highlightjs_input_filter
  - linkit
  - maxlength
  - media
  - menu_link_content
  - node
  - scheduler
  - scheduler_content_moderation_integration
  - tagify
  - ui_icons_menu
  - views_rss
  - views_rss_core
  - views_rss_media
config:
  # strict:
  #   - field.storage.comment.field_content
  #   - field.storage.node.field_bibliography
  #   - field.storage.node.field_comments
  actions:
    highlightjs_input_filter.settings:
      simpleConfigUpdate:
        enable_copy_button: true
        theme: a11y-dark
    user.role.anonymous:
      grantPermissions:
        - 'view media'
    user.role.authenticated:
      grantPermissions:
        - 'view media'
    user.role.content_editor:
      grantPermissions:
        - 'create blog content'
        - 'delete own blog content'
        - 'edit own blog content'
        - 'view media'
        - 'schedule publishing of nodes'
        - 'schedule publishing of taxonomy_term'
        - 'view scheduled content'
        - 'view scheduled taxonomy_term'
